import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blandford Welcome Group</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Blandford Welcome Group</h1>

        <p>
          We're a new group dedicated to helping settle a refugee family in
          Blandford Form. As of 6th June 2021 this is a new website which we'll
          be adding content to regularly. Please check back for updates.
        </p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
